[package]
name = "polars-python"
version = "0.1.0"
edition = "2021"

[lib]
name="polars_testing"
# crate-type = ["cdylib", "rlib"]

[dependencies]
polars = { version = "0.42.0", features = ["lazy"] }
